# Generated by Django 3.2.25 on 2024-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authormodel',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AddField(
            model_name='authormodel',
            name='about_en',
            field=models.TextField(null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='about_uz',
            field=models.TextField(null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='position_en',
            field=models.CharField(max_length=100, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='position_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='profession_en',
            field=models.CharField(max_length=100, null=True, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='profession_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='about',
            field=models.TextField(verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='position',
            field=models.CharField(max_length=100, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='profession',
            field=models.CharField(max_length=100, verbose_name='profession'),
        ),
    ]
