# Generated by Django 3.2.25 on 2024-06-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20240607_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='image',
            field=models.ImageField(upload_to='blog-authors', verbose_name='image'),
        ),
    ]
