# Generated by Django 3.2.25 on 2024-06-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_authormodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormodel',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='about_uz',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='position_uz',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='profession_en',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='profession_uz',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='author_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.authormodel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='author_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.authormodel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='category_en',
            field=models.ManyToManyField(null=True, related_name='blogs', to='blogs.BlogCategoryModel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='category_uz',
            field=models.ManyToManyField(null=True, related_name='blogs', to='blogs.BlogCategoryModel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image_en',
            field=models.ImageField(null=True, upload_to='blog-images'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='blog-images'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='short_info_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='short_info_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags_en',
            field=models.ManyToManyField(null=True, related_name='tags', to='blogs.BlogTagModel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags_uz',
            field=models.ManyToManyField(null=True, related_name='tags', to='blogs.BlogTagModel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
