# Generated by Django 3.2.25 on 2024-06-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='image',
            field=models.ImageField(upload_to='blog-authors'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='profession',
            field=models.CharField(max_length=100),
        ),
    ]
