# Generated by Django 3.2.25 on 2024-06-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20240607_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogtagmodel',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='authormodel',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='position_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='position_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='profession_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='profession_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
