# Generated by Django 3.2.25 on 2024-06-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
