# Generated by Django 5.0.6 on 2024-09-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordermodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='phone',
        ),
    ]
