# Generated by Django 3.2.25 on 2024-06-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcommentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCommentModel',
        ),
    ]
