# Generated by Django 3.2.25 on 2024-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_productcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmanufacture',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmanufacture',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_uz',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_info_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_info_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsizemodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsizemodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
