# Generated by Django 3.2.25 on 2024-06-10 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_productcommentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcommentmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcommentmodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcommentmodel',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productcommentmodel',
            name='message_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productcommentmodel',
            name='message_uz',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productcommentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
