# Generated by Django 3.2.25 on 2024-06-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240610_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcommentmodel',
            name='post',
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.productmodel'),
            preserve_default=False,
        ),
    ]
